# Copyright (c) 2021 Nick Winans
# SPDX-License-Identifier: MIT

# 更改键盘默认显示名称
CONFIG_ZMK_KEYBOARD_NAME="Dayu k30 Dongle"

# Dongle插USB，不需要省电，关闭空闲超时
CONFIG_ZMK_IDLE_TIMEOUT=0

# 启用 NKRO（全键无冲）
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# 配置蓝牙控制器的发射功率
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 注意：BT_MAX_CONN 和 BT_MAX_PAIRED 在 Kconfig.defconfig 中设置

# 测试：只启用I2C总线和OLED硬件节点，不编译显示驱动
CONFIG_I2C=y
# CONFIG_ZMK_DISPLAY=y

# USB日志功能配置
CONFIG_SERIAL=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_CDC_ACM_RINGBUF_SIZE=16384

# 日志配置
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_MAX_LEVEL=4
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# I2C调试日志
CONFIG_I2C_LOG_LEVEL_DBG=y
