# Copyright (c) 2021 Nick Winans
# SPDX-License-Identifier: MIT

# 更改键盘默认显示名称
CONFIG_ZMK_KEYBOARD_NAME="Dayu k30 Dongle"

# Dongle插USB，不需要省电，关闭空闲超时
CONFIG_ZMK_IDLE_TIMEOUT=0

# 启用 NKRO（全键无冲）
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# 配置蓝牙控制器的发射功率
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# OLED 显示屏配置
CONFIG_ZMK_DISPLAY=y
